name: Send Stock Data Email

on:
  schedule:
    - cron: '0 22 * * 1-5'  # 4:30 PM EST
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    env:
      pp: ${{secrets.PP}}
      smail: ${{secrets.SMAIL}}
      rmail: ${{secrets.RMAIL}}

    steps:
      - name: Checkout data-store branch
        uses: actions/checkout@v3
        with:
          ref: data-store
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
   
      - name: Install dependencies
        run: pip install -r requirements.txt
          
      - name: Run Sender and Cleanup
        run: python send_and_clean.py

      - name: Commit and push CSV deletions
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -u
          git commit -m "Cleaned up sent CSV files on $(date -u)" || echo "No changes to commit"
          git push origin data-store
